package model;

import java.io.Serializable;
import java.util.Date;

public class BasicDataSet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator .
     * This field corresponds to the database column basic_data_set.basic_data_set_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Integer basicDataSetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.superior_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Integer superiorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.code
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.name
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.creator
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.create_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.amender
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Integer amender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data_set.amend_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.basic_data_set_id
     *
     * @return the value of basic_data_set.basic_data_set_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Integer getBasicDataSetId() {
        return basicDataSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.basic_data_set_id
     *
     * @param basicDataSetId the value for basic_data_set.basic_data_set_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setBasicDataSetId(Integer basicDataSetId) {
        this.basicDataSetId = basicDataSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.superior_id
     *
     * @return the value of basic_data_set.superior_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Integer getSuperiorId() {
        return superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.superior_id
     *
     * @param superiorId the value for basic_data_set.superior_id
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setSuperiorId(Integer superiorId) {
        this.superiorId = superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.code
     *
     * @return the value of basic_data_set.code
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.code
     *
     * @param code the value for basic_data_set.code
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.name
     *
     * @return the value of basic_data_set.name
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.name
     *
     * @param name the value for basic_data_set.name
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.creator
     *
     * @return the value of basic_data_set.creator
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.creator
     *
     * @param creator the value for basic_data_set.creator
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.create_time
     *
     * @return the value of basic_data_set.create_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.create_time
     *
     * @param createTime the value for basic_data_set.create_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.amender
     *
     * @return the value of basic_data_set.amender
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.amender
     *
     * @param amender the value for basic_data_set.amender
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data_set.amend_time
     *
     * @return the value of basic_data_set.amend_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data_set.amend_time
     *
     * @param amendTime the value for basic_data_set.amend_time
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasicDataSet other = (BasicDataSet) that;
        return (this.getBasicDataSetId() == null ? other.getBasicDataSetId() == null : this.getBasicDataSetId().equals(other.getBasicDataSetId()))
            && (this.getSuperiorId() == null ? other.getSuperiorId() == null : this.getSuperiorId().equals(other.getSuperiorId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBasicDataSetId() == null) ? 0 : getBasicDataSetId().hashCode());
        result = prime * result + ((getSuperiorId() == null) ? 0 : getSuperiorId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", basicDataSetId=").append(basicDataSetId);
        sb.append(", superiorId=").append(superiorId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}