package mapper;

import model.BasicDataSet;
import model.BasicDataSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicDataSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    long countByExample(BasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByExample(BasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByPrimaryKey(Integer basicDataSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insert(BasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insertSelective(BasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    List<BasicDataSet> selectByExample(BasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    BasicDataSet selectByPrimaryKey(Integer basicDataSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasicDataSet record, @Param("example") BasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExample(@Param("record") BasicDataSet record, @Param("example") BasicDataSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKeySelective(BasicDataSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data_set
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKey(BasicDataSet record);
}