package mapper;

import model.Reserve;
import model.ReserveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    long countByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByPrimaryKey(Integer reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insert(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insertSelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    List<Reserve> selectByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    Reserve selectByPrimaryKey(Integer reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Reserve record, @Param("example") ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExample(@Param("record") Reserve record, @Param("example") ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKeySelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKey(Reserve record);
}