package mapper;

import model.UserCourse;
import model.UserCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    long countByExample(UserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByExample(UserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int deleteByPrimaryKey(Integer userCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insert(UserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int insertSelective(UserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    List<UserCourse> selectByExample(UserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    UserCourse selectByPrimaryKey(Integer userCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserCourse record, @Param("example") UserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByExample(@Param("record") UserCourse record, @Param("example") UserCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKeySelective(UserCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course
     *
     * @mbg.generated Mon Dec 31 09:59:50 CST 2018
     */
    int updateByPrimaryKey(UserCourse record);
}